#!/bin/bash
# Modified for Sungsan Mobile GIS by Sungsan on 2026-08-19.

set -euo pipefail

echo "building for ${triplet} on Qt ${install_qt_version} (${install_qt_arch})"

export SOURCE_DIR=/usr/src/qfield
python3 "${SOURCE_DIR}/scripts/check-sungsan-build-inputs.py"

CMAKE_BUILD_DIR="${QFIELD_CMAKE_BUILD_DIR:-/usr/src/qfield/build-${triplet}}"
ANDROID_NDK_VERSION=$(sed -En -e 's/^Pkg.Revision\s*=\s*([0-9a-f]+)/\1/p' ${ANDROID_NDK_HOME}/source.properties)
ANDROID_BUILD_TOOLS_VERSION="${ANDROID_BUILD_TOOLS_VERSION:-35.0.1}"
NINJA_PATH="$(command -v ninja || true)"
if [[ -z "${NINJA_PATH}" || ! -x "${NINJA_PATH}" ]]; then
	echo "오류: Android 빌드 이미지에 Ninja 실행 파일이 없습니다." >&2
	exit 12
fi

[[ -z ${APP_NAME:-} ]] && APP_NAME="QField Home"
[[ -z ${APP_PACKAGE_NAME:-} ]] && APP_PACKAGE_NAME="qfield_home"
[[ -z ${APP_PACKAGE_ID:-} ]] && APP_PACKAGE_ID="ch.opengis.${APP_PACKAGE_NAME}"
APP_UPSTREAM_REVISION="${APP_UPSTREAM_REVISION:-}"
[[ -z ${APP_ICON:-} ]] && APP_ICON="qfield_logo_beta"
APP_ICON_PATH="${APP_ICON_PATH:-}"
APP_SPLASH_PATH="${APP_SPLASH_PATH:-}"
APP_THEME_PATH="${APP_THEME_PATH:-}"
APP_DEFAULT_LANGUAGE="${APP_DEFAULT_LANGUAGE:-}"
APP_BUNDLED_PLUGINS="${APP_BUNDLED_PLUGINS:-}"
APP_POSITIONING_CHANNEL_NAME="${APP_POSITIONING_CHANNEL_NAME:-}"
APP_POSITIONING_CHANNEL_DESCRIPTION="${APP_POSITIONING_CHANNEL_DESCRIPTION:-}"
APP_POSITIONING_NOTIFICATION_TITLE="${APP_POSITIONING_NOTIFICATION_TITLE:-}"
APP_POSITIONING_NOTIFICATION_RUNNING_TEXT="${APP_POSITIONING_NOTIFICATION_RUNNING_TEXT:-}"
APP_CLOUD_CHANNEL_NAME="${APP_CLOUD_CHANNEL_NAME:-}"
APP_CLOUD_CHANNEL_DESCRIPTION="${APP_CLOUD_CHANNEL_DESCRIPTION:-}"
APP_CLOUD_NOTIFICATION_TITLE="${APP_CLOUD_NOTIFICATION_TITLE:-}"
APP_CLOUD_NOTIFICATION_RUNNING_TEXT="${APP_CLOUD_NOTIFICATION_RUNNING_TEXT:-}"
WITH_SAMPLE_PROJECTS="${WITH_SAMPLE_PROJECTS:-ON}"

echo "Package name ${APP_PACKAGE_NAME} (Android ID: ${APP_PACKAGE_ID})"

if [[ "${APP_PACKAGE_ID}" == "kr.co.sungsan.mobilegis" ]]; then
	if [[ "${SUNG_SAN_RELEASE_BUILD:-}" != "0" && "${SUNG_SAN_RELEASE_BUILD:-}" != "1" ]]; then
		echo "오류: SUNG_SAN_RELEASE_BUILD는 성산 빌드에서 0 또는 1이어야 합니다." >&2
		exit 10
	fi
	for forbidden_signing_variable in \
		STOREPASS \
		KEYNAME \
		KEYPASS \
		QT_ANDROID_KEYSTORE_PATH \
		QT_ANDROID_KEYSTORE_ALIAS \
		QT_ANDROID_KEYSTORE_STORE_PASS \
		QT_ANDROID_KEYSTORE_KEY_PASS; do
		if [[ -n "${!forbidden_signing_variable:-}" ]]; then
			echo "오류: 전체 성산 빌드 컨테이너에 서명 비밀을 전달할 수 없습니다." >&2
			exit 11
		fi
	done
fi

if [[ ${SUNG_SAN_CONFIGURE_VWORLD:-OFF} == ON ]]; then
	cmake \
		-D SOURCE_DIR="${SOURCE_DIR}/branding/sungsan/plugins/sungsan_vworld" \
		-D OUTPUT_DIR="${SOURCE_DIR}/build-sungsan-native-generated/plugins" \
		-P "${SOURCE_DIR}/branding/sungsan/configure-vworld-plugin.cmake"
fi

# Configure and install deps
cmake -S "${SOURCE_DIR}" \
	-B "${CMAKE_BUILD_DIR}" \
	-G Ninja \
	-D CMAKE_MAKE_PROGRAM:FILEPATH="${NINJA_PATH}" \
	-D CMAKE_BUILD_TYPE="${CMAKE_BUILD_TYPE:-Release}" \
	-D VCPKG_TARGET_TRIPLET="${triplet}" \
	-D ANDROID_NDK_VERSION="${ANDROID_NDK_VERSION}" \
	-D ANDROID_SDK_ROOT="${ANDROID_SDK_ROOT}" \
	-D ANDROID_BUILD_TOOLS_VERSION="${ANDROID_BUILD_TOOLS_VERSION}" \
	-D WITH_SPIX=OFF \
	-D APK_VERSION_CODE="${APK_VERSION_CODE}" \
	-D APP_VERSION="${APP_VERSION:-0}" \
	-D APP_VERSION_STR="${APP_VERSION_STR}" \
	-D APP_PACKAGE_NAME="${APP_PACKAGE_NAME}" \
	-D APP_PACKAGE_ID="${APP_PACKAGE_ID}" \
	-D APP_UPSTREAM_REVISION="${APP_UPSTREAM_REVISION}" \
	-D APP_ICON="${APP_ICON}" \
	-D APP_ICON_PATH="${APP_ICON_PATH}" \
	-D APP_SPLASH_PATH="${APP_SPLASH_PATH}" \
	-D APP_THEME_PATH="${APP_THEME_PATH}" \
	-D APP_DEFAULT_LANGUAGE="${APP_DEFAULT_LANGUAGE}" \
	-D APP_URL_SCHEME="${APP_URL_SCHEME:-qfield}" \
	-D APP_DATA_DIR_NAME="${APP_DATA_DIR_NAME:-QField}" \
	-D APP_POSITIONING_CHANNEL_NAME="${APP_POSITIONING_CHANNEL_NAME}" \
	-D APP_POSITIONING_CHANNEL_DESCRIPTION="${APP_POSITIONING_CHANNEL_DESCRIPTION}" \
	-D APP_POSITIONING_NOTIFICATION_TITLE="${APP_POSITIONING_NOTIFICATION_TITLE}" \
	-D APP_POSITIONING_NOTIFICATION_RUNNING_TEXT="${APP_POSITIONING_NOTIFICATION_RUNNING_TEXT}" \
	-D APP_CLOUD_CHANNEL_NAME="${APP_CLOUD_CHANNEL_NAME}" \
	-D APP_CLOUD_CHANNEL_DESCRIPTION="${APP_CLOUD_CHANNEL_DESCRIPTION}" \
	-D APP_CLOUD_NOTIFICATION_TITLE="${APP_CLOUD_NOTIFICATION_TITLE}" \
	-D APP_CLOUD_NOTIFICATION_RUNNING_TEXT="${APP_CLOUD_NOTIFICATION_RUNNING_TEXT}" \
	-D APP_BUNDLED_PLUGINS="${APP_BUNDLED_PLUGINS}" \
	-D WITH_SAMPLE_PROJECTS="${WITH_SAMPLE_PROJECTS}" \
	-D WITH_ALL_FILES_ACCESS="${WITH_ALL_FILES_ACCESS:-OFF}" \
	-D SENTRY_DSN:STRING="${SENTRY_DSN:-}" \
	-D SENTRY_ENV:STRING="${SENTRY_ENV:-}" \
	-D APP_NAME="${APP_NAME}" \
	-D VCPKG_INSTALL_OPTIONS="--allow-unsupported" \
	${NUGET_TOKEN:+-D NUGET_TOKEN=${NUGET_TOKEN}} \
	${NUGET_USERNAME:+-D NUGET_USERNAME=${NUGET_USERNAME}}

# Build app
cmake --build "${CMAKE_BUILD_DIR}"

# Package app
cmake --build "${CMAKE_BUILD_DIR}" --target bundle --config Release
